-- 1) perfiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

-- 2) categorías
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('equipment', 'space')),
  created_at timestamptz not null default now()
);

-- 3) inventario
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  status text not null default 'available' check (status in ('available', 'loaned', 'maintenance', 'pending', 'approved', 'rejected', 'returned')),
  type text not null default 'equipment' check (type in ('equipment', 'space')),
  category_id bigint references public.categories(id),
  quantity integer not null default 1,
  created_at timestamptz not null default now()
);

-- 4) préstamos
create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.items(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'returned')),
  created_at timestamptz not null default now()
);

-- RLS
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.items enable row level security;
alter table public.loans enable row level security;

-- perfiles: cada usuario ve su propio perfil; admins ven todo
create policy "profiles_select_own_or_admin"
on public.profiles
for select
using (
  auth.uid() = id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

create policy "profiles_update_own_or_admin"
on public.profiles
for update
using (
  auth.uid() = id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  auth.uid() = id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- categorías e inventario: lectura pública para todos autenticados
create policy "items_read_all_auth"
on public.items
for select
using (auth.role() = 'authenticated');

create policy "items_admin_write"
on public.items
for all
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy "categories_read_all_auth"
on public.categories
for select
using (auth.role() = 'authenticated');

create policy "categories_admin_write"
on public.categories
for all
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- préstamos: usuarios leen sus préstamos; admins leen todos
create policy "loans_select_own_or_admin"
on public.loans
for select
using (
  auth.uid() = user_id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy "loans_insert_own"
on public.loans
for insert
with check (auth.uid() = user_id);

create policy "loans_update_admin_only"
on public.loans
for update
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- datos base
insert into public.categories (name, type)
values
  ('Laptop', 'equipment'),
  ('Proyector', 'equipment'),
  ('Audio', 'equipment'),
  ('Aula', 'space'),
  ('Sala', 'space')
on conflict do nothing;

insert into public.items (name, description, status, type, category_id, quantity)
select 'Laptop Dell Latitude', 'Laptop para trabajo y clases', 'available', 'equipment', c.id, 1
from public.categories c where c.name = 'Laptop' and c.type = 'equipment'
on conflict do nothing;

insert into public.items (name, description, status, type, category_id, quantity)
select 'Proyector Epson', 'Equipo para presentaciones', 'available', 'equipment', c.id, 1
from public.categories c where c.name = 'Proyector' and c.type = 'equipment'
on conflict do nothing;

insert into public.items (name, description, status, type, category_id, quantity)
select 'Aula 204', 'Aula para reuniones y clases', 'available', 'space', c.id, 1
from public.categories c where c.name = 'Aula' and c.type = 'space'
on conflict do nothing;
